/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { ExperienceUpdateManyWithoutUserProfilesInput } from "./ExperienceUpdateManyWithoutUserProfilesInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ProjectUpdateManyWithoutUserProfilesInput } from "./ProjectUpdateManyWithoutUserProfilesInput";
import { SocialLinkUpdateManyWithoutUserProfilesInput } from "./SocialLinkUpdateManyWithoutUserProfilesInput";

@InputType()
class UserProfileUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => ExperienceUpdateManyWithoutUserProfilesInput,
  })
  @ValidateNested()
  @Type(() => ExperienceUpdateManyWithoutUserProfilesInput)
  @IsOptional()
  @Field(() => ExperienceUpdateManyWithoutUserProfilesInput, {
    nullable: true,
  })
  experiences?: ExperienceUpdateManyWithoutUserProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  photo?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ProjectUpdateManyWithoutUserProfilesInput,
  })
  @ValidateNested()
  @Type(() => ProjectUpdateManyWithoutUserProfilesInput)
  @IsOptional()
  @Field(() => ProjectUpdateManyWithoutUserProfilesInput, {
    nullable: true,
  })
  projects?: ProjectUpdateManyWithoutUserProfilesInput;

  @ApiProperty({
    required: false,
    type: () => SocialLinkUpdateManyWithoutUserProfilesInput,
  })
  @ValidateNested()
  @Type(() => SocialLinkUpdateManyWithoutUserProfilesInput)
  @IsOptional()
  @Field(() => SocialLinkUpdateManyWithoutUserProfilesInput, {
    nullable: true,
  })
  socialLinks?: SocialLinkUpdateManyWithoutUserProfilesInput;
}

export { UserProfileUpdateInput as UserProfileUpdateInput };
