/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { ExperienceCreateNestedManyWithoutUserProfilesInput } from "./ExperienceCreateNestedManyWithoutUserProfilesInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ProjectCreateNestedManyWithoutUserProfilesInput } from "./ProjectCreateNestedManyWithoutUserProfilesInput";
import { SocialLinkCreateNestedManyWithoutUserProfilesInput } from "./SocialLinkCreateNestedManyWithoutUserProfilesInput";

@InputType()
class UserProfileCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => ExperienceCreateNestedManyWithoutUserProfilesInput,
  })
  @ValidateNested()
  @Type(() => ExperienceCreateNestedManyWithoutUserProfilesInput)
  @IsOptional()
  @Field(() => ExperienceCreateNestedManyWithoutUserProfilesInput, {
    nullable: true,
  })
  experiences?: ExperienceCreateNestedManyWithoutUserProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  photo?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ProjectCreateNestedManyWithoutUserProfilesInput,
  })
  @ValidateNested()
  @Type(() => ProjectCreateNestedManyWithoutUserProfilesInput)
  @IsOptional()
  @Field(() => ProjectCreateNestedManyWithoutUserProfilesInput, {
    nullable: true,
  })
  projects?: ProjectCreateNestedManyWithoutUserProfilesInput;

  @ApiProperty({
    required: false,
    type: () => SocialLinkCreateNestedManyWithoutUserProfilesInput,
  })
  @ValidateNested()
  @Type(() => SocialLinkCreateNestedManyWithoutUserProfilesInput)
  @IsOptional()
  @Field(() => SocialLinkCreateNestedManyWithoutUserProfilesInput, {
    nullable: true,
  })
  socialLinks?: SocialLinkCreateNestedManyWithoutUserProfilesInput;
}

export { UserProfileCreateInput as UserProfileCreateInput };
